import datetime
import re
from pathlib import Path

# Resolve path relative to this script: ../src/version.py
BASE_DIR = Path(__file__).resolve().parent.parent
VERSION_FILE = BASE_DIR / "src" / "version.py"


def get_next_build_number() -> int:
    """Extracts and increments the build number from the existing file."""
    if not VERSION_FILE.exists():
        return 1

    content = VERSION_FILE.read_text()
    match = re.search(r"BUILD_NUMBER = (\d+)", content)
    return int(match.group(1)) + 1 if match else 1


def main() -> None:
    """Generates the versioning artifact."""
    build_no = get_next_build_number()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f'''"""Automated version artifact generated by pre-commit."""
# This file is automatically generated. Do not edit manually.

VERSION = "0.1.{build_no}"
BUILD_TIMESTAMP = "{timestamp}"
BUILD_NUMBER = {build_no}
'''
    # Ensure src directory exists
    VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)

    VERSION_FILE.write_text(content)
    print(f"Generated version 0.1.{build_no} at {timestamp}")


if __name__ == "__main__":
    main()
